@import Foundation;


typedef NSString * VerifoneSDKPaymentTypeValue NS_EXTENSIBLE_STRING_ENUM;

extern VerifoneSDKPaymentTypeValue const _Nonnull VerifoneSDKPaymentTypeValueCreditCard;
extern VerifoneSDKPaymentTypeValue const _Nonnull VerifoneSDKPaymentTypeValuePaypal;
extern VerifoneSDKPaymentTypeValue const _Nonnull VerifoneSDKPaymentTypeValueApplePay;
extern VerifoneSDKPaymentTypeValue const _Nonnull VerifoneSDKPaymentTypeValueKlarna;
extern VerifoneSDKPaymentTypeValue const _Nonnull VerifoneSDKPaymentTypeValueSwish;
extern VerifoneSDKPaymentTypeValue const _Nonnull VerifoneSDKPaymentTypeValueVipps;
extern VerifoneSDKPaymentTypeValue const _Nonnull VerifoneSDKPaymentTypeValueMobilePay;
